### ISSUE TITLE
Feature Request: Auto-sleep for rate limiting

### ISSUE THREAD

**Issue by hoelzro** [semifor/Twitter-API#11]
I was wondering if there would be interest a role to automatically sleep the necessary amount of time when a rate limit error is encountered.  I wrote up a little role to do this - let me know if I should make a PR to share it!

**Comment by hoelzro** [comment]
@semifor Any thoughts on this idea?

**Comment by semifor** [comment]
I missed your original post. Thanks for pinging me.

I'd be interested in seeing the role. If it can be made general enough it would be a nice addition.Do you have your role is git repository? If not, care to share it in a gist so we chat about it?

If you're an IRC user, you can find me in #net-twitter on irc.perl.org.

**Comment by hoelzro** [comment]
@semifor Here's the role: https://gist.github.com/hoelzro/87e3fcbe66b15a3694ff0c2a8d2972a5

It's very minimal right now, and could definitely be more flexible, but it's a start!

**Comment by hoelzro** [comment]
Excellent - PR is [here](https://github.com/semifor/Twitter-API/pull/12)

**Comment by hoelzro** [comment]
I'm going to go ahead and close this, since you merged the PR!
