### ISSUE TITLE
some fix for POD

### ISSUE THREAD

**Issue by gypark** [semifor/Twitter-API#16]
Hello,

I recently began to use Twitter::API and thank you so much for the good module.

When I was reading documents, I found some typo or invalid links.

https://metacpan.org/pod/Twitter::API::Error
In Synopsis,

    die $_ unless is_twitter_api_error;
    # is_twitter_api_error does not seem to use $_ when no argument was passed. It should be
    die $_ unless is_twitter_api_error($_);

https://metacpan.org/pod/Twitter::API::Trait::ApiMethods

    new_direct_message([ $text, [ $screen_name | $user_id, ]][ \%args ])
    https://dev.twitter.com/rest/reference/post/direct_messages/new

    new_direct_messages_event([ $text, [ $recipient_id, ]][ \%args ])
    https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-message

The first link is not valid, and the second link is a doc for `new_direct_message`. They shoule be:

    new_direct_message([ $text, [ $screen_name | $user_id, ]][ \%args ])
    https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-message

    new_direct_messages_event([ $text, [ $recipient_id, ]][ \%args ])
    https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event

Thank you!

**Comment by semifor** [comment]
Thank you. I broke an arm recently so likely won't tackle this until I can get both hands on the keyboard again. Running a text editor is an exercise in frustration.

I'd happily accept a pull request for the typos if you're up to it, but that's entirely optional.

I recently accepted a pull request with new Direct Messages support. It may resolve the DM link issues. I'll look into that, too.

**Comment by semifor** [comment]
@gypark I just released Twitter::API 1.0004. It includes your synopsis fix. Links to Twitter documentation have been updated. And documentation for the old direct messages endpoints has been removed. Those methods now throw deprecation errors.

Thanks for your help with this!
