### ISSUE TITLE
Doesn't handle newfangled long tweets

### ISSUE THREAD

**Issue by kantarjiev** [semifor/Twitter-API#29]
When I call `user_timeline`, I get an array of tweets that are truncated at 140 characters, even though the system now supports up to 280 characters.

**Comment by semifor** [comment]
Hi @kantarjiev. You need to pass `tweet_mode => 'extended'`. Then you'll find the 280 character text in the `full_text` field.

The `tweet_mode` option has two possible values: `extended` and `compat`. If you don't explicitly pass a value, it defaults to `compat` which preserves backward compatibility for code that expected 140 characters.

That used to be adequately documented in the Twitter API reference but now it takes some searching.

Here's a simple example:
```perl
    my $r = $client->user_timeline({ screen_name => 'twitter', tweet_mode => 'extended' });
    say $r->[0]{full_text};
```

**Comment by kantarjiev** [comment]
Awesome! Thanks for the pointer - I really did go digging through the docs.
