### ISSUE TITLE
"599 Internal Exception" handling?

### ISSUE THREAD

**Issue by GuguKatze** [semifor/Twitter-API#30]
I keep getting a "599 Internal Exception at /usr/share/perl5/Twitter/API.pm line 362" warning every other week or so. Maybe add an option to make them not fatal?

Using Version 1.0005 from the Ubuntu 20.04.3 LTS repos.
/usr/share/perl5/Twitter/API.pm
Installed: 1.0005
CPAN:      1.0006  Not up to date

**Comment by semifor** [comment]
Are you using the [RetryOnError](https://github.com/semifor/Twitter-API/blob/master/lib/Twitter/API/Trait/RetryOnError.pm) trait? It should handle this as a temporary error and automatically retry.

**Comment by GuguKatze** [comment]
Thank you kind stranger. I was not aware of this trait.
