### ISSUE TITLE
Documentation Request: Async Event loop example

### ISSUE THREAD

**Issue by spazm** [semifor/Twitter-API#7]
The docs mention that Twitter::API can be used with event loop based code.  I think an example would be neat. Maybe a minimal async bot?

What's the status of `Twitter::API::AnyEvent`?  It's mentioned in the POD, but isn't included in the distribution.

**Comment by jabowery** [comment]
[The metacpan description](https://metacpan.org/pod/Twitter::API#DESCRIPTION) says:

```
Some features are _provided by **separate distributions**_ to avoid additional dependencies most users won't want or need:

async support via subclass Twitter::API::AnyEvent

inflate API call results to objects via Twitter::API::Trait::InflateObjects
```
They are hyperlinked to dead pages and no indication of what "distributions" are referred to.

**Comment by semifor** [comment]
I'd forgotten these modules had never been distributed. They exist on GitHub but need POD and tests before they're ready for distribution. I've updated the links to these modules to point to their GitHub repositories rather than the non-existent distributions until they are distributed.
